<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
	<ForceDesignerDPIUnaware>true</ForceDesignerDPIUnaware>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>analysis_examination_scrutiny_deliberation_scanning_perusal_icon_146775.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject />
  </PropertyGroup>
  <ItemGroup>
    <Content Include="analysis_examination_scrutiny_deliberation_scanning_perusal_icon_146775.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(ProjectDir)$(OutDir)samples&quot;&#xD;&#xA;copy &quot;$(ProjectDir)samples&quot; &quot;$(ProjectDir)$(OutDir)samples&quot;&#xD;&#xA;copy &quot;$(ProjectDir)*.xml&quot; &quot;$(ProjectDir)$(OutDir)&quot;" />
  </Target>
</Project>